### ISSUE TITLE
Root: Difference between PC and smartphone

### ISSUE THREAD

**Issue by maniusq** [madaidans-insecurities/madaidans-insecurities.github.io#17]
I also have root rights on a PC. What makes smartphones so dangerous that root rights are not recommended there?

**Comment by beerisgood** [comment]
> In addition, root fundamentally breaks verified boot and other security features by placing excessive trust in persistent state. By rooting your device, you are breaking Android's security model and adding further layers of trust where it is inappropriate.

**Comment by maniusq** [comment]
Sounds like this is identical to secure boot from the PC 🤔

**Comment by beerisgood** [comment]
> Sounds like this is identical to secure boot from the PC 🤔

verified boot is much better ;)

**Comment by maniusq** [comment]
Well, both ensure that system-relevant files are not manipulated. Are there any other features?

So there is basically no big difference between root on PC and Android?

**Comment by madaidan** [comment]
This is already explained in the article. Root is equally dangerous on desktop as it is on mobile, if not even more so. Desktop systems do not have an equivalent security model to Android, hence why root access is more commonplace on such systems. It is still a security risk nonetheless and must be restricted in security-sensitive environments.

**Comment by maniusq** [comment]
That is exactly why I'm asking. In that case, root access should be allowed even less often on a PC, or it should be handled as restrictively as Android, but that's not the case. I therefore wonder why this is the case and why there are no systems that do this similarly to Android.

Why is the issue closed???

**Comment by madaidan** [comment]
I have already explained this clearly. You've consistently ignored what has been said in this thread and the others.
