### ISSUE TITLE
Mention Pipewire in Linux hardening guide

### ISSUE THREAD

**Issue by FieryBinary** [madaidans-insecurities/madaidans-insecurities.github.io#36]
You already mentioned how PulseAudio is insecure, and to use standard ALSA utilities instead. However, that might not be feasible for many users.

What do you think of Pipewire? It's written with security in mind, and it works well out-of-the-box. It's still early in development.

Website: https://pipewire.org/

**Comment by ldo** [comment]
In what way is PulseAudio insecure? Its [list of CVEs](https://www.cvedetails.com/vulnerability-list/vendor_id-6346/Pulseaudio.html), going back about the last decade and a half, seems very short.

**Comment by Akkowicz** [comment]
https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/AccessControl/

Pulseaudio was not written with security in mind, it runs almost unrestricted in user-context and any app can snoop on another application's audio.

**Comment by madaidans-insecurities** [comment]
Thanks; added by https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/commit/29fa22faf03d4af90b218fe4e3b2d536a6ced566.

**Comment by ldo** [comment]
Can’t see any mention of PulseAudio or PipeWire in that commit.

**Comment by madaidans-insecurities** [comment]
https://madaidans-insecurities.github.io/guides/linux-hardening.html#pulseaudio

> [PulseAudio](https://www.freedesktop.org/wiki/Software/PulseAudio/) is a common sound server, but it was not written with isolation or sandboxing in mind, making it a recurring sandbox escape vulnerability. To prevent this, it is recommended to block access to PulseAudio from within your sandbox or uninstall it from your system entirely. You can use the [standard ALSA utilities](https://alsa-project.org/wiki/Main_Page) or [PipeWire](https://pipewire.org/) instead.
