### ISSUE TITLE
Update Android section now that Pixel 6 and 6 Pro is out

### ISSUE THREAD

**Issue by Shepherd115** [madaidans-insecurities/madaidans-insecurities.github.io#40]
The Android page conclusion (https://madaidans-insecurities.github.io/android.html#conclusion) should be updated now that Pixels have dumped Qualcomm SoC and using Tensor instead. Also TitanM2

**Comment by madaidans-insecurities** [comment]
Fixed by https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/commit/29fa22faf03d4af90b218fe4e3b2d536a6ced566.
