### ISSUE TITLE
Links not accessible

### ISSUE THREAD

**Issue by RandPotato** [madaidans-insecurities/madaidans-insecurities.github.io#42]
The links in the website are put in a way that makes them not so accessible. This article is an example of links that aren't accessible https://madaidans-insecurities.github.io/firefox-chromium.html#security-researcher-views 
See the MDN Web Docs For [link best practices](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#link_best_practices
)

**Comment by Zanthed** [comment]
What's inaccessible about them? Maybe to a screen reader, yeah. Maybe the spaces aren't big enough, yeah.

But the point in that style was for emphasis. Emphasise the fact that multiple security researchers share the same views in a new link in each word and to emphasis that it's a widely shared view by multiple security researchers.

Or what do you suggest would be better to do that can achieve the same emphasis, if not, better?

**Comment by RandomPotato5367** [comment]
According to the MDN link I shared earlier, usually people using screen readers jump around links. Thus, a link's text should be understandable by itself, without reading any other text or links.
The example I shared says
__Many__ __security__ __experts__ __also__ __share__ __these__ __views__ __about__ __Firefox.__
Where every word is a link, making each link not understandable at all when you read it by itself.

**Comment by madaidans-insecurities** [comment]
That section was recently restructured by https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/commit/29fa22faf03d4af90b218fe4e3b2d536a6ced566. Is this still a problem?

**Comment by RandPotato** [comment]
I think it looks awesome now.
BTW I wanted to make it clear that I don't have any form of disability.
It's just that I thought it would be a kind and nice thing to make the site easier to navigate for people with disabilities (specifically people using screen readers in this case).
