### ISSUE TITLE
404 on hide-hardware-info script URL

### ISSUE THREAD

**Issue by glitsj16** [madaidans-insecurities/madaidans-insecurities.github.io#44]
Hi, I really enjoyed reading this very comprehensive guide. Just wanted to inform you that the hide-hardware-info script URL 404's:

https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/blob/7ff52a976db0d22d987959015e4b0729316054b7/guides/linux-hardening.html#L785

The correct one:
https://github.com/Whonix/security-misc/blob/master/usr/libexec/security-misc/hide-hardware-info

Regards

**Comment by madaidans-insecurities** [comment]
Thanks; fixed by https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/commit/29fa22faf03d4af90b218fe4e3b2d536a6ced566.
