### ISSUE TITLE
Missing RLBox libaries 

### ISSUE THREAD

**Issue by vord1080** [madaidans-insecurities/madaidans-insecurities.github.io#51]
Your analysis of Firefox vs Chromium security says RLBox is only used to sandbox three libraries, the [announcement blog post](https://hacks.mozilla.org/2021/12/webassembly-and-back-again-fine-grained-sandboxing-in-firefox-95/) claims that it is currently applied to five libraries (and the dependencies of those libraries). Please address this inaccuracy, thank you.

**Comment by madaidans-insecurities** [comment]
Thanks; fixed by https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/commit/5f18aea3e79bd02257a1aa42af2918d386c14071.
